language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - mysql
  - postgresql
env:
  - DJANGO=1.11 DB=sqlite
  - DJANGO=1.11 DB=mysql
  - DJANGO=1.11 DB=postgres
  - DJANGO=2.0 DB=sqlite
  - DJANGO=2.0 DB=mysql
  - DJANGO=2.0 DB=postgres
  - DJANGO=2.1 DB=sqlite
  - DJANGO=2.1 DB=mysql
  - DJANGO=2.1 DB=postgres

before_script:
  - mysql -e 'create database sqlutil;'
  - psql -c 'create database sqlutil;' -U postgres
install:
  - pip install pip --upgrade
  - if [[ "$DB" == "mysql" && ("$DJANGO" == "1.11" || "$DJANGO" == "2.0") ]]; then pip install mysqlclient\<=1.3.13; fi
  - if [ "$DB" == "mysql" && "$DJANGO" == "2.1" ]; then pip install mysqlclient; fi
  - if [ "$DB" == "postgres" ]; then pip install psycopg2; fi
  - pip install -q Django==$DJANGO
script:
  - python runtests.py --settings=sql_util.tests.test_"$DB"_settings